# Generated by Django 3.2.13 on 2022-06-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cashBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='currentBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='initialBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
