# Generated by Django 3.2.13 on 2022-06-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220606_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='currentBalance',
        ),
    ]
