# Generated by Django 3.2.13 on 2022-07-04 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_accountbal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbal',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
