# Generated by Django 3.2.13 on 2022-07-13 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_accountbal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('bank', models.CharField(default='Default Bank', max_length=10)),
                ('change', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
